include ../Makefile.in
CUR_DIR := $(shell pwd)
RELATIVE_PATH := $(shell realpath --relative-to=$(PLATFORM_SAMPLES_DIR) $(CUR_DIR))

.PHONY: all clean install

all:
	@echo "Build sample_imu_iio and sample_imu_input in subdirectories."

clean:
	@echo "Clean sample_imu_iio and sample_imu_input in subdirectories."

install:
	@echo "Install sample_imu_iio and sample_imu_input from subdirectories."
